strength: 55
vitality: 50
int: 70
wisdom: 60
c_rate: 20
# m_res: 130
m_res: 160
m_speed: 30
evasion: 120
dexterity: 70
agility: 70
evasion: 120
acc: 120
m_acc: 120
p_atk: 600
m_atk: 600
# look at 16_30_05_03_05_22