strength: 50
vitality: 50
int: 70
wisdom: 70
c_rate: 20
m_res: 120
m_speed: 30
evasion: 120
dexterity: 70
agility: 70
evasion: 120
acc: 120
m_acc: 120
p_atk: 800
# look at 16_30_05_03_05_22