strength: 60
vitality: 40
int: 70
wisdom: 60
c_rate: 14
m_res: 120
m_speed: 16
evasion: 120
dexterity: 70
agility: 50
acc: 100
# m_acc: 60
p_atk: 600
m_atk: 500
# look at 16_30_05_03_05_22